cat("Loading packages...\n")
library(ggplot2)
library(vioplot)
library(corrplot)
library(polycor)
library(RMySQL)
library(caret)
library(tidyr)
library(properties)
library(e1071)
library(pROC)
library(gridExtra)
library(magrittr)
library(MASS)
library(gbm)
library(bnclassify)
library(C50)
library(kernlab)
library(xgboost)
library(testthat)
library(Hmisc)
library(data.table)
library(plyr)
library(dplyr)
cat("Packages loaded\n")

# Logging
library(logging)
basicConfig()

loginfo('Source loaded.')